# Generated by Django 6.1.1 on 2026-09-16 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('n_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='encargado_curso',
            fields=[
                ('encargado_id', models.AutoField(primary_key=True, serialize=False)),
                ('n_encargado', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('n_usuario', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='curso',
            fields=[
                ('curso_id', models.AutoField(primary_key=True, serialize=False)),
                ('n_curso', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('valor_curso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos_app.categoria')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos_app.encargado_curso')),
            ],
        ),
    ]
