# Generated by Django 6.1.1 on 2026-09-16 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
