# Generated by Django 6.1.1 on 2026-09-23 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0004_recreate_encargado_curso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido_curso',
            name='curso',
            field=models.ForeignKey(db_column='n_curso', on_delete=django.db.models.deletion.CASCADE, to='cursos_app.curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='encargado',
            field=models.ForeignKey(db_column='profesor', on_delete=django.db.models.deletion.CASCADE, to='cursos_app.encargado_curso'),
        ),
        migrations.AlterField(
            model_name='encargado_curso',
            name='profesor',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='curso',
            field=models.ForeignKey(db_column='n_curso', on_delete=django.db.models.deletion.CASCADE, to='cursos_app.curso'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='usuario',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
