# Generated by Django 6.1.1 on 2026-09-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0005_alter_contenido_curso_curso_alter_curso_encargado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('idioma_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_idioma', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pais',
            fields=[
                ('pais_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=100)),
            ],
        ),
    ]
